name = "my-express-app"
main = "dist/index.js" # or build output file
compatibility_date = "2025-10-21"

[build]
command = "npm run build" # if you use TypeScript or bundler

[site]
bucket = "./public" # optional, for static assets

[vars]
NODE_ENV = "production"

[observability]
enabled = true
